### ISSUE TITLE
Duplicate Sentences in WorldTree

### ISSUE THREAD

**Issue by yangky11** [allenai/entailment_bank#15]
Hi,

Thank you for updating the evaluation code for Task 3. I recently noticed that there are duplicate sentences in WorldTree. Some of them are identical, others have minor differences such as uppercase vs. lowercase. For example,
```
ET_addon:985": "earth is a kind of planet"
"e473-7297-61c1-56fa": Earth is a kind of planet"

"ET_addon:2237": "one can get something from a source"
"e6fb-12a1-939d-e850": one can get something from a source"
```

I wonder if the current evaluation code is robust to this artifact. What happens if the predicted sentence is correct but with a different uuid?

**Comment by yangky11** [comment]
I think the uuid in the output form of Task 3 might be redundant. The evaluation code should only look at the sentence?

**Comment by OyvindTafjord** [comment]
Thanks for the feedback! Yes, there is indeed some unintentional duplication in the corpus. 

The evaluation script does actually only look at the sentence and ignores the uuid field, so it's optional to include it.

The evaluation is currently unfortunately sensitive to minor changes in the sentence, like the "earth" vs "Earth" above. Ideally that would not be the case, so I would consider this a bug in the current version. The effect should be minor though (and could be worked around by some preprocessing).

**Comment by yangky11** [comment]
Thanks!
