### ISSUE TITLE
Prediction Files for Results in the Paper

### ISSUE THREAD

**Issue by yangky11** [allenai/entailment_bank#6]
Hi Bhavana,

Thanks for updating the code with the models! Is it possible to also include the prediction files of T5-large and T5-11B on both the validation data and the test data? Thanks!

Best,

**Comment by bhavanadalvi** [comment]
@yangky11 Thanks Kaiyu for your interest in this work. I have uploaded the prediction files at: https://github.com/allenai/entailment_bank/tree/main/data/processed_data/predictions/emnlp_2021

**Comment by yangky11** [comment]
That's really helpful. Thanks!
